# Generated by Django 4.0.4 on 2022-04-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVATIBLE', 'Avatible'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='AVATIBLE', max_length=15),
        ),
    ]
