# Generated by Django 4.0.4 on 2022-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
