# Generated by Django 4.0.4 on 2022-04-20 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0003_alter_ticket_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
